### ISSUE TITLE
Core modules could not have sources on fs

### ISSUE THREAD

**Issue by floatdrop** [quorrajs/Ouch#3]
When exception thrown from async operation [this code ](https://github.com/quorrajs/Ouch/blob/master/exception/frame.js#L89) trys to read `events.js` and crashes:

```
ERR! index.js (dev) ENOENT, no such file or directory 'events.js'
ERR! index.js (dev)     at Object.fs.openSync (fs.js:439:18)
ERR! index.js (dev)     at Object.fs.readFileSync (fs.js:290:15)
ERR! index.js (dev)     at Object.frame.__proto__.getFileContents (/home/floatdrop/test-project/server/node_modules/ouch/exception/frame.js:89:47)
ERR! index.js (dev)     at Object.frame.__proto__.getFileLines (/home/floatdrop/test-project/server/node_modules/ouch/exception/frame.js:39:33)
ERR! index.js (dev)     at __line (eval at <anonymous> (/home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:55:29)
ERR! index.js (dev)     at Array.forEach (native)
ERR! index.js (dev)     at eval (eval at <anonymous> (/home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:14:15)
ERR! index.js (dev)     at /home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:482:14
ERR! index.js (dev)     at include (/home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:480:39)
ERR! index.js (dev)     at eval (eval at <anonymous> (/home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:29:21)
ERR! index.js (dev)     at /home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:482:14
ERR! index.js (dev)     at Object.exports.render (/home/floatdrop/test-project/server/node_modules/ouch/node_modules/ejs/lib/ejs.js:316:13)
ERR! index.js (dev)     at TemplateHelper.render (/home/floatdrop/test-project/server/node_modules/ouch/util/TemplateHelper.js:65:16)
ERR! index.js (dev)     at PrettyPageHandler.handle (/home/floatdrop/test-project/server/node_modules/ouch/handler/PrettyPageHandler.js:143:34)
ERR! index.js (dev)     at next (/home/floatdrop/test-project/server/node_modules/ouch/Ouch.js:132:29)
ERR! index.js (dev)     at /home/floatdrop/test-project/server/node_modules/ouch/Ouch.js:139:9
```

Shouldn't it be wrapped in `try {} catch`?

**Comment by harishanchu** [comment]
If running node is installed via nvm there is a chance to have nodes source files in the system in the NVM_DIR, there for Ouch will check whether files exist in system and refer them in Pretty Page Handler. If NVM_DIR is not defined in the nodejs environment, null should be returned, which was missing and caused the error. Thanks for notifying.
